language: node_js
node_js:
  - "stable"
cache:
  directories:
    - frontend/node_modules
install:
    - cd frontend/
    - npm install
before_script:
  - cd frontend/
script:
  - CI=1 npm test
on:
  branch: master