config:
  firebase:
    database:
      url: "https://e-wall-board.firebaseio.com/"
      projectId: "e-wall-board"

---

spring:
  profiles: prod

config:
  firebase:
    database:
      url: "https://e-wall-prod.firebaseio.com"
      projectId: "e-wall-prod"
