config:
  firebase:
    database:
      url: "https://e-wall-board.firebaseio.com"
      projectId: "e-wall-board"
server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false

---

spring:
  profiles: prod

config:
  firebase:
    database:
      url: "https://e-wall-prod.firebaseio.com"
      projectId: "e-wall-prod"
