config:
  firebase:
    database:
      url: "https://e-wall-board.firebaseio.com/"
      projectId: "e-wall-board"
server:
  port: ${PORT:8080}

---

spring:
  profiles: prod

config:
  firebase:
    database:
      url: "https://e-wall-prod.firebaseio.com"
      projectId: "e-wall-prod"
